app = 'rentesla-api'
primary_region = 'iad'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8080'
  TESLA_TOKEN_NAME = 'rentesla_production'
  TEST_MODE = 'False'
  MOCK_TESLA_API = 'False'
  DEBUG = 'False'
  LOG_LEVEL = 'INFO'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = '1s'
    interval = '15s'
    restart_limit = 0
    timeout = '2s'
    method = 'get'
    path = '/health'

[vm]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = 'rentesla_data'
  destination = '/data'

[processes]
  app = 'python app.py'

[[statics]]
  guest_path = '/.well-known/appspecific/'
  url_prefix = '/.well-known/appspecific/' 